
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to utilise'
        required: false
        type: string
        
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      release_build: true

  release:
    name: Release
    needs: ci
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch build artifacts
        uses: actions/download-artifact@v2
        with:
          path: release-assets/
