
name: Build

on:
  push:
    branches: [release_artifacts]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      release_build: false

  release:
    name: Release
    needs: ci
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch build artifacts
        uses: actions/download-artifact@v2
        with:
          path: release-assets/

      - run: ls -al release-assets
